import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';
import '../theme/app_colors.dart';

enum NotificationType {
  serviceDue,
  ticketAssigned,
  ticketUpdated,
  paymentOverdue,
  warrantyExpiring,
  dealUpdated,
  leadFollowUp,
  taskAssigned,
  taskCompleted,
  stockPullRequired,
  leaveRequested,
  leaveApproved,
  leaveRejected,
  lateArrival,
  expensePending,
  expenseApproved,
  expenseRejected,
  stockOutRequested,
  stockOutApproved,
  stockOutRejected,
  perDiemPending,
  perDiemApproved,
  perDiemRejected,
  perDiemPaid,
  poPending,
  poApproved,
  poRejected,
  lowStockAlert,
  tenderDeadline,
  tenderOverdue,
  deviceRenewal,
  system,
}

extension NotificationTypeX on NotificationType {
  String get label => switch (this) {
    NotificationType.serviceDue         => 'Service Due',
    NotificationType.ticketAssigned     => 'Ticket Assigned',
    NotificationType.ticketUpdated      => 'Ticket Updated',
    NotificationType.paymentOverdue     => 'Payment Overdue',
    NotificationType.warrantyExpiring   => 'Warranty Expiring',
    NotificationType.dealUpdated        => 'Deal Updated',
    NotificationType.leadFollowUp       => 'Follow-up Due',
    NotificationType.taskAssigned       => 'Task Assigned',
    NotificationType.taskCompleted      => 'Task Completed',
    NotificationType.stockPullRequired  => 'Stock Pull Required',
    NotificationType.leaveRequested     => 'Leave Requested',
    NotificationType.leaveApproved      => 'Leave Approved',
    NotificationType.leaveRejected      => 'Leave Rejected',
    NotificationType.lateArrival        => 'Running Late',
    NotificationType.expensePending     => 'Expense Pending Approval',
    NotificationType.expenseApproved    => 'Expense Approved',
    NotificationType.expenseRejected    => 'Expense Rejected',
    NotificationType.stockOutRequested  => 'Stock-Out Requested',
    NotificationType.stockOutApproved   => 'Stock-Out Approved',
    NotificationType.stockOutRejected   => 'Stock-Out Rejected',
    NotificationType.perDiemPending     => 'Per-Diem Pending Approval',
    NotificationType.perDiemApproved    => 'Per-Diem Approved',
    NotificationType.perDiemRejected    => 'Per-Diem Rejected',
    NotificationType.perDiemPaid        => 'Per-Diem Paid',
    NotificationType.poPending          => 'Purchase Order Pending Approval',
    NotificationType.poApproved         => 'Purchase Order Approved',
    NotificationType.poRejected         => 'Purchase Order Rejected',
    NotificationType.lowStockAlert      => 'Low Stock',
    NotificationType.tenderDeadline     => 'Tender Deadline',
    NotificationType.tenderOverdue      => 'Tender Deadline Overdue',
    NotificationType.deviceRenewal      => 'Registration Renewal',
    NotificationType.system             => 'System',
  };

  /// Grouping bucket used for categorized display (bell dropdown + full page).
  String get category => switch (this) {
    NotificationType.leaveRequested     => 'Approvals',
    NotificationType.stockOutRequested  => 'Approvals',
    NotificationType.perDiemPending     => 'Approvals',
    NotificationType.expensePending     => 'Approvals',
    NotificationType.serviceDue         => 'Service',
    NotificationType.ticketAssigned     => 'Service',
    NotificationType.ticketUpdated      => 'Service',
    NotificationType.warrantyExpiring   => 'Service',
    NotificationType.stockPullRequired  => 'Service',
    NotificationType.paymentOverdue     => 'Sales',
    NotificationType.dealUpdated        => 'Sales',
    NotificationType.leadFollowUp       => 'Sales',
    NotificationType.taskAssigned       => 'HR',
    NotificationType.taskCompleted      => 'HR',
    NotificationType.leaveApproved      => 'HR',
    NotificationType.leaveRejected      => 'HR',
    NotificationType.lateArrival        => 'HR',
    NotificationType.expenseApproved    => 'Updates',
    NotificationType.expenseRejected    => 'Updates',
    NotificationType.stockOutApproved   => 'Updates',
    NotificationType.stockOutRejected   => 'Updates',
    NotificationType.perDiemApproved    => 'Updates',
    NotificationType.perDiemRejected    => 'Updates',
    NotificationType.perDiemPaid        => 'Updates',
    NotificationType.poPending          => 'Approvals',
    NotificationType.poApproved         => 'Updates',
    NotificationType.poRejected         => 'Updates',
    NotificationType.lowStockAlert      => 'Service',
    NotificationType.tenderDeadline     => 'Updates',
    NotificationType.tenderOverdue      => 'Updates',
    NotificationType.deviceRenewal      => 'Updates',
    NotificationType.system             => 'System',
  };

  /// Label for the notification's action button, or null when the
  /// notification is purely informational (no action to take).
  String? get actionLabel => switch (this) {
    NotificationType.leaveRequested     => 'Review & Approve',
    NotificationType.stockOutRequested  => 'Review & Approve',
    NotificationType.perDiemPending     => 'Review & Approve',
    NotificationType.expensePending     => 'Review & Approve',
    NotificationType.ticketAssigned     => 'View Ticket',
    NotificationType.ticketUpdated      => 'View Ticket',
    NotificationType.serviceDue         => 'View Ticket',
    NotificationType.leadFollowUp       => 'View Lead',
    NotificationType.dealUpdated        => 'View Lead',
    NotificationType.taskAssigned       => 'View Task',
    NotificationType.taskCompleted      => 'View Task',
    NotificationType.leaveApproved      => 'View',
    NotificationType.leaveRejected      => 'View',
    NotificationType.expenseApproved    => 'View',
    NotificationType.expenseRejected    => 'View',
    NotificationType.stockOutApproved   => 'View',
    NotificationType.stockOutRejected   => 'View',
    NotificationType.perDiemApproved    => 'View',
    NotificationType.perDiemRejected    => 'View',
    NotificationType.perDiemPaid        => 'View',
    NotificationType.poPending          => 'Review & Approve',
    NotificationType.poApproved         => 'View',
    NotificationType.poRejected         => 'View',
    NotificationType.lateArrival        => null,
    NotificationType.paymentOverdue     => null,
    NotificationType.warrantyExpiring   => null,
    NotificationType.stockPullRequired  => null,
    NotificationType.lowStockAlert      => null,
    NotificationType.tenderDeadline     => 'View Tender',
    NotificationType.tenderOverdue      => 'View Tender',
    NotificationType.deviceRenewal      => 'View Registration',
    NotificationType.system             => null,
  };

  IconData get icon => switch (this) {
    NotificationType.serviceDue        => Symbols.build,
    NotificationType.ticketAssigned    => Symbols.confirmation_number,
    NotificationType.ticketUpdated     => Symbols.update,
    NotificationType.paymentOverdue    => Symbols.warning,
    NotificationType.warrantyExpiring  => Symbols.workspace_premium,
    NotificationType.dealUpdated       => Symbols.trending_up,
    NotificationType.leadFollowUp      => Symbols.hourglass_top,
    NotificationType.taskAssigned      => Symbols.assignment_ind,
    NotificationType.taskCompleted     => Symbols.task_alt,
    NotificationType.stockPullRequired => Symbols.inventory_2,
    NotificationType.leaveRequested    => Symbols.event_busy,
    NotificationType.leaveApproved     => Symbols.event_available,
    NotificationType.leaveRejected     => Symbols.event_busy,
    NotificationType.lateArrival       => Symbols.schedule,
    NotificationType.expensePending    => Symbols.receipt_long,
    NotificationType.expenseApproved   => Symbols.check_circle,
    NotificationType.expenseRejected   => Symbols.cancel,
    NotificationType.stockOutRequested => Symbols.output,
    NotificationType.stockOutApproved  => Symbols.check_circle,
    NotificationType.stockOutRejected  => Symbols.cancel,
    NotificationType.perDiemPending    => Symbols.payments,
    NotificationType.perDiemApproved   => Symbols.check_circle,
    NotificationType.perDiemRejected   => Symbols.cancel,
    NotificationType.perDiemPaid       => Symbols.payments,
    NotificationType.poPending         => Symbols.local_shipping,
    NotificationType.poApproved        => Symbols.check_circle,
    NotificationType.poRejected        => Symbols.cancel,
    NotificationType.lowStockAlert     => Symbols.production_quantity_limits,
    NotificationType.tenderDeadline    => Symbols.gavel,
    NotificationType.tenderOverdue     => Symbols.report,
    NotificationType.deviceRenewal     => Symbols.event_repeat,
    NotificationType.system            => Symbols.info,
  };

  Color get color => switch (this) {
    NotificationType.serviceDue        => AppColors.amber,
    NotificationType.ticketAssigned    => AppColors.teal,
    NotificationType.ticketUpdated     => AppColors.blue,
    NotificationType.paymentOverdue    => AppColors.coral,
    NotificationType.warrantyExpiring  => AppColors.amber,
    NotificationType.dealUpdated       => AppColors.violet,
    NotificationType.leadFollowUp      => AppColors.amber,
    NotificationType.taskAssigned      => AppColors.blue,
    NotificationType.taskCompleted     => AppColors.teal,
    NotificationType.stockPullRequired => AppColors.violet,
    NotificationType.leaveRequested    => AppColors.amber,
    NotificationType.leaveApproved     => AppColors.teal,
    NotificationType.leaveRejected     => AppColors.coral,
    NotificationType.lateArrival       => AppColors.amber,
    NotificationType.expensePending    => AppColors.amber,
    NotificationType.expenseApproved   => AppColors.teal,
    NotificationType.expenseRejected   => AppColors.coral,
    NotificationType.stockOutRequested => AppColors.amber,
    NotificationType.stockOutApproved  => AppColors.teal,
    NotificationType.stockOutRejected  => AppColors.coral,
    NotificationType.perDiemPending    => AppColors.amber,
    NotificationType.perDiemApproved   => AppColors.teal,
    NotificationType.perDiemRejected   => AppColors.coral,
    NotificationType.perDiemPaid       => AppColors.teal,
    NotificationType.poPending         => AppColors.amber,
    NotificationType.poApproved        => AppColors.teal,
    NotificationType.poRejected        => AppColors.coral,
    NotificationType.lowStockAlert     => AppColors.amber,
    NotificationType.tenderDeadline    => AppColors.amber,
    NotificationType.tenderOverdue     => AppColors.coral,
    NotificationType.deviceRenewal     => AppColors.amber,
    NotificationType.system            => AppColors.textMute,
  };
}

NotificationType _parseType(String s) => switch (s) {
  'ticket_assigned'      => NotificationType.ticketAssigned,
  'ticket_updated'       => NotificationType.ticketUpdated,
  'payment_overdue'      => NotificationType.paymentOverdue,
  'warranty_expiring'    => NotificationType.warrantyExpiring,
  'deal_updated'         => NotificationType.dealUpdated,
  'lead_follow_up'       => NotificationType.leadFollowUp,
  'task_assigned'        => NotificationType.taskAssigned,
  'task_completed'       => NotificationType.taskCompleted,
  'stock_pull_required'  => NotificationType.stockPullRequired,
  'leave_requested'      => NotificationType.leaveRequested,
  'leave_approved'       => NotificationType.leaveApproved,
  'leave_rejected'       => NotificationType.leaveRejected,
  'late_arrival'         => NotificationType.lateArrival,
  'expense_requested'    => NotificationType.expensePending,
  'expense_escalated'    => NotificationType.expensePending,
  'expense_approved'     => NotificationType.expenseApproved,
  'expense_rejected'     => NotificationType.expenseRejected,
  'stock_out_requested'  => NotificationType.stockOutRequested,
  'stock_out_approved'   => NotificationType.stockOutApproved,
  'stock_out_rejected'   => NotificationType.stockOutRejected,
  'per_diem_requested'   => NotificationType.perDiemPending,
  'per_diem_forwarded'   => NotificationType.perDiemPending,
  'per_diem_approved'    => NotificationType.perDiemApproved,
  'per_diem_rejected'    => NotificationType.perDiemRejected,
  'per_diem_paid'         => NotificationType.perDiemPaid,
  'po_submitted'          => NotificationType.poPending,
  'po_sales_approved'     => NotificationType.poPending,
  'po_director_reviewed'  => NotificationType.poPending,
  'po_payment_initiated'  => NotificationType.poPending,
  'po_approved'           => NotificationType.poApproved,
  'po_rejected'           => NotificationType.poRejected,
  'low_stock_alert'       => NotificationType.lowStockAlert,
  'tender_deadline'       => NotificationType.tenderDeadline,
  'tender_overdue'        => NotificationType.tenderOverdue,
  'device_renewal'        => NotificationType.deviceRenewal,
  'system'               => NotificationType.system,
  _                      => NotificationType.serviceDue,
};

class AppNotification {
  final int    id;
  final NotificationType type;
  final String title;
  final String body;
  final String? entityType;
  final String? entityId;
  final bool   isRead;
  final String createdAt;

  const AppNotification({
    required this.id,
    required this.type,
    required this.title,
    required this.body,
    this.entityType,
    this.entityId,
    this.isRead = false,
    required this.createdAt,
  });

  factory AppNotification.fromJson(Map<String, dynamic> j) => AppNotification(
    id:         (j['id'] as num).toInt(),
    type:       _parseType(j['type'] as String? ?? 'system'),
    title:      j['title']      as String? ?? '',
    body:       j['body']       as String? ?? j['message'] as String? ?? '',
    entityType: j['entity_type'] as String?,
    entityId:   j['entity_id']?.toString(),
    isRead:     j['is_read'] as bool? ?? j['read'] as bool? ?? false,
    createdAt:  j['created_at'] as String? ?? '',
  );
}
